### ISSUE TITLE
Initial requirements

### ISSUE THREAD

**Issue by VladimirGrenaderov** [webpack-contrib/dynamic-css-loader#1]
My first proposals. 

Loader options:
- **useable** - same as style-loader option
- **insertAt** - same as style-loader option
- **singleton** - same as style-loader option
- **attrs** - same as style-loader option
- **crossorigin** - same as Webpack config option
- **cacheLinks** - boolean, enable/disable link nodes caching on detach/attach if **singleton** = false. I haven't strong reasons to disable caching, but it may be helpful to reload changed CSS in dev environment without reload entire page.

Browser-side loader API:
- **use(callback)** - attaches CSS into DOM and calls the callback(error, styleSheet) when it ready. Callback may be omitted.
- **unuse()** - detaches CSS from DOM.

May be attach/detach pair sounds better?

**Comment by bebraw** [comment]
attach/detach would sound like a good pair to me. Maybe crossOrigin over crossorigin to follow naming of the rest?

I guess the next step would be to write tests and implementation for each. I'll add schema based validation (a PR) for those options later today. Maybe you can start typing tests. 👍

**Comment by VladimirGrenaderov** [comment]
Yep, let it be **crossOrigin** and **attach**/**detach**

**Comment by VladimirGrenaderov** [comment]
Sorry, I'm working on Badoo project right now, so I'll start coding a bit later, at Moscow night. And yes, my reviews may be _slightly_ not polite - it's professional deformation + bad English, plz keep in mind ;)

**Comment by bebraw** [comment]
No probs. Take your time. I think you know the technical parts for this better than me. 👍

**Comment by VladimirGrenaderov** [comment]
Hello! @bebraw, I'm new with loader-runner, but seems it doesn't handle some errors inside schema-utils. When I run
```javascript
export default function dynamicCSSLoader(content) {
  const options = loaderUtils.getOptions(this);
  const validation = validateSchema(schema, options);
  return 'AAAA';
```

I saw no res.result field in runLoaders callback. But if I set return statement at top, runLoaders result contains expected 'AAAA'. In both cases jest works without any errors. Could you help me?

**Comment by bebraw** [comment]
@VladimirGrenaderov Can you link me to a branch to study? If validation fails somehow, it should probably show up in `err`.

**Comment by VladimirGrenaderov** [comment]
@bebraw Hello! I returned, really crazy month... I hope to finish this project in May :)

**Comment by bebraw** [comment]
@VladimirGrenaderov It's cool. Thanks for the update. I've been really busy too (touring Europe).

**Comment by VladimirGrenaderov** [comment]
Some options are not required now:
- useable: this is dynamic loader, so nobody will use it without provided api
- singleton: no reasons to keep this option, I just haven't real examples
- cacheLinks: need performance test, in latest Chrome I can't see differences. May be later
