### ISSUE TITLE
Custom output file name

### ISSUE THREAD

**Issue by VladimirGrenaderov** [webpack-contrib/dynamic-css-loader#3]
**name** loader option, passed in loaderUtils.interpolateName

Default value should be a neutral like [path][name].[ext]

**Comment by VladimirGrenaderov** [comment]
@bebraw , what if we used chain like dynamic-css-loader!**file-loader**!extract-loader to allow users customize generated file names as they wish? I think this is a better solution then trying to emulate file-loader's logic.

**Comment by bebraw** [comment]
@VladimirGrenaderov That sounds fine. It will take a slight change in **dynamic-css-loader**, but that's ok I think.
